# Build / verify HaploCatcher-source.R (the standalone, source-able copy) from
# the package's R/ directory. The R/ directory is the single source of truth;
# this script only concatenates it.
#
# Usage (run from the package root):
#   Rscript tools/build_single_source.R          # (re)write HaploCatcher-source.R
#   Rscript tools/build_single_source.R --check   # exit 1 if it is out of date
#
# The git pre-commit hook in tools/git-hooks/pre-commit calls the --check form.

# the R/ files to stitch together, helpers first then the exported functions
.hc_source_files <- function() {
  c("R/utils-internal.R",
    "R/locus_cv.R",
    "R/locus_train.R",
    "R/locus_pred.R",
    "R/locus_perm_cv.R",
    "R/plot_locus_perm_cv.R",
    "R/auto_locus.R")
}

# the fixed file header: usage notes, a soft dependency check, and a %dopar% shim
.hc_source_header <- function() {
  c("# =============================================================================",
    "# HaploCatcher - single-file source",
    "# -----------------------------------------------------------------------------",
    "# A directly source-able copy of the whole package. Source it with:",
    "#     source(\"HaploCatcher-source.R\")",
    "# It defines every exported function and the hidden .hc_* helpers, with",
    "# roxygen documentation retained above each function.",
    "#",
    "# Requires: caret, randomForest, foreach, doParallel, parallel, ggplot2,",
    "#           patchwork, knitr, graphics, stats",
    "#",
    "# AUTO-GENERATED by tools/build_single_source.R from R/ -- do not hand-edit.",
    "# =============================================================================",
    "",
    "local({",
    "  deps <- c(\"caret\", \"randomForest\", \"foreach\", \"doParallel\", \"parallel\",",
    "            \"ggplot2\", \"patchwork\", \"knitr\")",
    "  miss <- deps[!vapply(deps, requireNamespace, logical(1), quietly = TRUE)]",
    "  if (length(miss)) warning(\"HaploCatcher: missing packages: \", paste(miss, collapse = \", \"))",
    "})",
    "",
    "if (requireNamespace(\"foreach\", quietly = TRUE) && !exists(\"%dopar%\"))",
    "  `%dopar%` <- foreach::`%dopar%`",
    "")
}

# (hidden) assemble the single-file source as a character vector of lines.
# When `write = TRUE` it also writes `path`. Returns the lines invisibly so the
# checker can compare without touching disk.
.hc_build_single_source <- function(path = "HaploCatcher-source.R", write = TRUE) {
  # the header is fixed; the body is each R/ file under a section banner
  header <- .hc_source_header()
  # stitch the R/ files together with a banner naming each source file
  body <- unlist(lapply(.hc_source_files(), function(f)
    c("", paste0("# ===== ", f, " ====="), "", readLines(f))))
  # the full file is header followed by body
  lines <- c(header, body)
  # optionally write it out
  if (write) {
    writeLines(lines, path)
    message("Wrote ", path, " (", length(lines), " lines).")
  }
  # return the lines invisibly for the checker
  invisible(lines)
}

# (hidden) verify the on-disk single-file source matches a fresh build of R/.
# Returns TRUE invisibly when in sync, FALSE (with a message) when stale/missing.
# Line-ending and trailing-newline differences are ignored (readLines strips them).
.hc_check_single_source <- function(path = "HaploCatcher-source.R") {
  # what the file *should* contain, built fresh from R/
  expected <- .hc_build_single_source(path = path, write = FALSE)
  # a missing file is treated as out of date
  if (!file.exists(path)) {
    message("MISSING: ", path, " -- run: Rscript tools/build_single_source.R")
    return(FALSE)
  }
  # the file's current contents
  actual <- readLines(path)
  # exact content comparison (EOL/trailing-newline agnostic)
  if (identical(expected, actual)) {
    message(path, " is in sync with R/.")
    invisible(TRUE)
  } else {
    message("OUT OF SYNC: ", path, " differs from R/ -- run: Rscript tools/build_single_source.R")
    FALSE
  }
}

# command-line dispatch: sys.nframe() == 0 only when run directly (e.g. via
# Rscript), not when this file is source()d to reuse the functions
if (sys.nframe() == 0L) {
  # parse the (optional) --check flag
  args <- commandArgs(trailingOnly = TRUE)
  if ("--check" %in% args) {
    # verify mode: non-zero exit if out of date (used by the pre-commit hook)
    if (!isTRUE(.hc_check_single_source())) quit(status = 1L)
  } else {
    # default mode: rebuild the single-file source from R/
    .hc_build_single_source()
  }
}
