#' Model Gene Compendium Data Set
#'
#' A numeric matrix which contains molecular marker information on 1345 unique genotypes for 2271 SNP markers located on wheat chromosome 3B. This data set corresponds to the information found in the "gene_comp" and "marker_info" data sets.
#'
#' @format A numeric matrix with 1345 rows and 2271 columns:
#'
#' @source {Generated by Zachary James Winn for the CSU breeding program via historical in-house GBS data}
#'
#' @examples
#' data("geno_mat") #lazy loads the dataset for use in the package
"geno_mat"
